"""Add missing columns to knowledge_bases

Revision ID: 1a7d96fbcac9
Revises: 30b1c2d3e4f5
Create Date: 2026-05-15 22:50:13.517453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7d96fbcac9'
down_revision: Union[str, Sequence[str], None] = '30b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='ingestionjobstatus'), nullable=False),
    sa.Column('current_step', sa.Enum('CREATED', 'VALIDATING', 'PROMPT_INJECTION_CHECK', 'PARSING', 'DEDUPLICATING', 'VECTOR_INDEXING', 'GRAPH_INDEXING', 'MEDIA_PROCESSING', 'FINALIZING', name='ingestionstep'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('index_version', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('document_hash', sa.String(length=64), nullable=True))
    op.add_column('knowledge_bases', sa.Column('active_index_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('knowledge_bases', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('knowledge_bases', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'embedding_dimension')
    op.drop_column('knowledge_bases', 'embedding_model')
    op.drop_column('knowledge_bases', 'active_index_version')
    op.drop_column('documents', 'document_hash')
    op.drop_column('documents', 'embedding_dimension')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'index_version')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
